# Generated by Django 3.0.3 on 2020-02-13 13:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('cholesterol_in_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium_in_mg', models.IntegerField()),
                ('carbohydrates_in_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_in_grams', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('account_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('cook_time_in_min', models.IntegerField()),
                ('prep_time_in_min', models.IntegerField()),
                ('total_time_in_min', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('cuisine', models.CharField(max_length=256)),
                ('servings', models.IntegerField()),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.User')),
                ('nutrition_information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.NutritionalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('items', models.CharField(max_length=256)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.Recipes')),
            ],
        ),
    ]
