# Generated by Django 3.0.2 on 2020-02-01 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('account_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
