# Generated by Django 3.0.2 on 2020-02-01 22:59

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200201_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('cholesterol_in_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium_in_mg', models.IntegerField()),
                ('carbohydrates_in_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_in_grams', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'NutritionalInformation',
            },
        ),
        migrations.CreateModel(
            name='OrderedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('items', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'OrderedList',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cook_time_in_min', models.IntegerField()),
                ('prep_time_in_min', models.IntegerField()),
                ('total_time_in_min', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('cuisine', models.CharField(max_length=256)),
                ('servings', models.IntegerField()),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'db_table': 'Recipes',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
