# Generated by Django 3.0.3 on 2020-02-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
    ]
