# Generated by Django 3.0.2 on 2020-02-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200201_2311'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nutritionalinformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderedlist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recipes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
