# Generated by Django 3.0.3 on 2020-02-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='recipe',
        ),
    ]
